// <auto-generated />
using System;
using MediLink_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediLink_BackEnd.Migrations
{
    [DbContext(typeof(MediLinkContext))]
    [Migration("20260304160541_DataModels_V1")]
    partial class DataModels_V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IngredientMedication", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<int>("UsedInId")
                        .HasColumnType("int");

                    b.HasKey("IngredientsId", "UsedInId");

                    b.HasIndex("UsedInId");

                    b.ToTable("IngredientMedication");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.AppointmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonOfDenial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonOfRequest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialistDoctorId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("SpecialistDoctorId");

                    b.ToTable("AppointmentRequests");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.ContactInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactInfo");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Events");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.MedicalStaffDataSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("MedicalStaffDataSheets");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicationForm")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.PatientDataSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TAJNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PatientDataSheets");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Referal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CauseDiagnosisId")
                        .HasColumnType("int");

                    b.Property<bool>("CausesInabilityToWork")
                        .HasColumnType("bit");

                    b.Property<string>("ConsiliumAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsiliumQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("IssuingDate")
                        .HasColumnType("date");

                    b.Property<int>("IssuingDoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ReferedInstititionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CauseDiagnosisId");

                    b.HasIndex("IssuingDoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ReferedInstititionId");

                    b.ToTable("Referals");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CustomEventId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactInfoId");

                    b.HasIndex("CustomEventId");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PatientSpecialistDoctor", b =>
                {
                    b.Property<int>("PatientsId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialistDoctorsId")
                        .HasColumnType("int");

                    b.HasKey("PatientsId", "SpecialistDoctorsId");

                    b.HasIndex("SpecialistDoctorsId");

                    b.ToTable("PatientSpecialistDoctor");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Appointment", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.Event");

                    b.Property<int?>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<int?>("MedicalAsisstantId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PlaceOfVisitId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonOfVisit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialistDoctorId")
                        .HasColumnType("int");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("MedicalAsisstantId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PlaceOfVisitId");

                    b.HasIndex("SpecialistDoctorId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.CustomEvent", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.Event");

                    b.Property<int?>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MedicalAsisstantId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialistDoctorId")
                        .HasColumnType("int");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("MedicalAsisstantId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SpecialistDoctorId");

                    b.ToTable("CustomEvents");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.MedicationReminder", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.Event");

                    b.Property<int?>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<int>("AdministratorOfMedicineId")
                        .HasColumnType("int");

                    b.Property<int?>("MedicalAsisstantId")
                        .HasColumnType("int");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialistDoctorId")
                        .HasColumnType("int");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("AdministratorOfMedicineId");

                    b.HasIndex("MedicalAsisstantId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SpecialistDoctorId");

                    b.ToTable("MedicationReminders");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Administrator", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.User");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.MedicalAsisstant", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.User");

                    b.Property<int>("AttendingDoctorId")
                        .HasColumnType("int");

                    b.Property<int>("DataSheetId")
                        .HasColumnType("int");

                    b.HasIndex("AttendingDoctorId");

                    b.HasIndex("DataSheetId");

                    b.ToTable("MedicalAsisstants");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Patient", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.User");

                    b.Property<int>("DataSheetId")
                        .HasColumnType("int");

                    b.HasIndex("DataSheetId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.SpecialistDoctor", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.User");

                    b.Property<int>("DataSheetId")
                        .HasColumnType("int");

                    b.HasIndex("DataSheetId");

                    b.ToTable("SpecialistDoctors");
                });

            modelBuilder.Entity("IngredientMedication", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.Medication", null)
                        .WithMany()
                        .HasForeignKey("UsedInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.AppointmentRequest", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Patient", "Patient")
                        .WithMany("Requests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.SpecialistDoctor", "SpecialistDoctor")
                        .WithMany("PendingAppointments")
                        .HasForeignKey("SpecialistDoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("SpecialistDoctor");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Diagnosis", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Patient", "Patient")
                        .WithMany("Dignoses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Event", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.MedicalStaffDataSheet", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Medication", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Diagnosis", null)
                        .WithMany("PrescribedMedications")
                        .HasForeignKey("DiagnosisId");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Referal", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Diagnosis", "CauseDiagnosis")
                        .WithMany()
                        .HasForeignKey("CauseDiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.SpecialistDoctor", "IssuingDoctor")
                        .WithMany("IssuedReferals")
                        .HasForeignKey("IssuingDoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.Patient", "Patient")
                        .WithMany("Referals")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.Institution", "ReferedInstitition")
                        .WithMany()
                        .HasForeignKey("ReferedInstititionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauseDiagnosis");

                    b.Navigation("IssuingDoctor");

                    b.Navigation("Patient");

                    b.Navigation("ReferedInstitition");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Symptom", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Diagnosis", null)
                        .WithMany("Symptoms")
                        .HasForeignKey("DiagnosisId");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.User", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.ContactInfo", "ContactInfo")
                        .WithMany()
                        .HasForeignKey("ContactInfoId");

                    b.HasOne("MediLink_BackEnd.Models.CustomEvent", null)
                        .WithMany("Attnedees")
                        .HasForeignKey("CustomEventId");

                    b.Navigation("ContactInfo");
                });

            modelBuilder.Entity("PatientSpecialistDoctor", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.SpecialistDoctor", null)
                        .WithMany()
                        .HasForeignKey("SpecialistDoctorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Appointment", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Administrator", null)
                        .WithMany("Appointments")
                        .HasForeignKey("AdministratorId");

                    b.HasOne("MediLink_BackEnd.Models.Event", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.Appointment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.MedicalAsisstant", null)
                        .WithMany("Appointments")
                        .HasForeignKey("MedicalAsisstantId");

                    b.HasOne("MediLink_BackEnd.Models.Patient", null)
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId");

                    b.HasOne("MediLink_BackEnd.Models.Institution", "PlaceOfVisit")
                        .WithMany()
                        .HasForeignKey("PlaceOfVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.SpecialistDoctor", "SpecialistDoctor")
                        .WithMany("Appointments")
                        .HasForeignKey("SpecialistDoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PlaceOfVisit");

                    b.Navigation("SpecialistDoctor");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.CustomEvent", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Administrator", null)
                        .WithMany("CustomEvents")
                        .HasForeignKey("AdministratorId");

                    b.HasOne("MediLink_BackEnd.Models.Event", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.CustomEvent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.MedicalAsisstant", null)
                        .WithMany("CustomEvents")
                        .HasForeignKey("MedicalAsisstantId");

                    b.HasOne("MediLink_BackEnd.Models.Patient", null)
                        .WithMany("CustomEvents")
                        .HasForeignKey("PatientId");

                    b.HasOne("MediLink_BackEnd.Models.SpecialistDoctor", null)
                        .WithMany("CustomEvents")
                        .HasForeignKey("SpecialistDoctorId");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.MedicationReminder", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Administrator", null)
                        .WithMany("MedicationReminders")
                        .HasForeignKey("AdministratorId");

                    b.HasOne("MediLink_BackEnd.Models.User", "AdministratorOfMedicine")
                        .WithMany("AsministeringMedication")
                        .HasForeignKey("AdministratorOfMedicineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.Event", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.MedicationReminder", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.MedicalAsisstant", null)
                        .WithMany("MedicationReminders")
                        .HasForeignKey("MedicalAsisstantId");

                    b.HasOne("MediLink_BackEnd.Models.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.Patient", null)
                        .WithMany("MedicationReminders")
                        .HasForeignKey("PatientId");

                    b.HasOne("MediLink_BackEnd.Models.SpecialistDoctor", null)
                        .WithMany("MedicationReminders")
                        .HasForeignKey("SpecialistDoctorId");

                    b.Navigation("AdministratorOfMedicine");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Administrator", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.User", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.MedicalAsisstant", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.SpecialistDoctor", "AttendingDoctor")
                        .WithMany("MedicalAsisstants")
                        .HasForeignKey("AttendingDoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.MedicalStaffDataSheet", "DataSheet")
                        .WithMany()
                        .HasForeignKey("DataSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.User", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.MedicalAsisstant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendingDoctor");

                    b.Navigation("DataSheet");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Patient", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.PatientDataSheet", "DataSheet")
                        .WithMany()
                        .HasForeignKey("DataSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.User", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.Patient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSheet");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.SpecialistDoctor", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.MedicalStaffDataSheet", "DataSheet")
                        .WithMany()
                        .HasForeignKey("DataSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.User", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.SpecialistDoctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSheet");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Diagnosis", b =>
                {
                    b.Navigation("PrescribedMedications");

                    b.Navigation("Symptoms");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.User", b =>
                {
                    b.Navigation("AsministeringMedication");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.CustomEvent", b =>
                {
                    b.Navigation("Attnedees");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Administrator", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CustomEvents");

                    b.Navigation("MedicationReminders");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.MedicalAsisstant", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CustomEvents");

                    b.Navigation("MedicationReminders");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CustomEvents");

                    b.Navigation("Dignoses");

                    b.Navigation("MedicationReminders");

                    b.Navigation("Referals");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.SpecialistDoctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CustomEvents");

                    b.Navigation("IssuedReferals");

                    b.Navigation("MedicalAsisstants");

                    b.Navigation("MedicationReminders");

                    b.Navigation("PendingAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
