// <auto-generated />
using System;
using MediLink_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediLink_BackEnd.Migrations
{
    [DbContext(typeof(MediLinkContext))]
    [Migration("20260330213534_DataModelCompleted")]
    partial class DataModelCompleted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IngredientMedication", b =>
                {
                    b.Property<int>("IngredientsID")
                        .HasColumnType("int");

                    b.Property<int>("UsedInMedicationsID")
                        .HasColumnType("int");

                    b.HasKey("IngredientsID", "UsedInMedicationsID");

                    b.HasIndex("UsedInMedicationsID");

                    b.ToTable("MedicationIngredient", (string)null);
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.AppointmentRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("ReasonOfDenial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonOfRequest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialistDoctorID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PatientID");

                    b.HasIndex("SpecialistDoctorID");

                    b.ToTable("AppointmentRequests");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.ContactInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ContactInfo");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.DataSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("DataSheets");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientID");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Events");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Ingredient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Institution", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Medication", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicationForm")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Referal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CauseDiagnosisId")
                        .HasColumnType("int");

                    b.Property<bool>("CausesInabilityToWork")
                        .HasColumnType("bit");

                    b.Property<string>("ConsiliumAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsiliumQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("IssuingDate")
                        .HasColumnType("date");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("ReferedInstititionID")
                        .HasColumnType("int");

                    b.Property<int>("SpecialistDoctorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CauseDiagnosisId");

                    b.HasIndex("PatientID");

                    b.HasIndex("ReferedInstititionID");

                    b.HasIndex("SpecialistDoctorID");

                    b.ToTable("Referals");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ContactInfoID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomEventID")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ContactInfoID");

                    b.HasIndex("CustomEventID");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MedicalAsisstantSpecialistDoctor", b =>
                {
                    b.Property<int>("AttendingDoctorsID")
                        .HasColumnType("int");

                    b.Property<int>("MedicalAsisstantsID")
                        .HasColumnType("int");

                    b.HasKey("AttendingDoctorsID", "MedicalAsisstantsID");

                    b.HasIndex("MedicalAsisstantsID");

                    b.ToTable("MedicalAsisstantSpecialistDoctor");
                });

            modelBuilder.Entity("PatientSpecialistDoctor", b =>
                {
                    b.Property<int>("PatientsID")
                        .HasColumnType("int");

                    b.Property<int>("SpecialistDoctorsID")
                        .HasColumnType("int");

                    b.HasKey("PatientsID", "SpecialistDoctorsID");

                    b.HasIndex("SpecialistDoctorsID");

                    b.ToTable("PatientSpecialistDoctor");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.MedicalStaffDataSheet", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.DataSheet");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstitutionID")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("InstitutionID");

                    b.ToTable("MedicalStaffDataSheets");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.PatientDataSheet", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.DataSheet");

                    b.Property<string>("TAJNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("PatientDataSheets");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Appointment", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.Event");

                    b.Property<int>("InstitutionID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("ReasonOfVisit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialistDoctorID")
                        .HasColumnType("int");

                    b.HasIndex("InstitutionID");

                    b.HasIndex("PatientID");

                    b.HasIndex("SpecialistDoctorID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.CustomEvent", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.Event");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CustomEvents");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.MedicationReminder", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.Event");

                    b.Property<int>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<int>("MedicationID")
                        .HasColumnType("int");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("MedicationID");

                    b.ToTable("MedicationReminders");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Administrator", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.User");

                    b.Property<int>("DataSheetID")
                        .HasColumnType("int");

                    b.HasIndex("DataSheetID");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.MedicalAsisstant", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.User");

                    b.Property<int>("DataSheetID")
                        .HasColumnType("int");

                    b.HasIndex("DataSheetID");

                    b.ToTable("MedicalAsisstants");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Patient", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.User");

                    b.Property<int>("DataSheetID")
                        .HasColumnType("int");

                    b.HasIndex("DataSheetID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.SpecialistDoctor", b =>
                {
                    b.HasBaseType("MediLink_BackEnd.Models.User");

                    b.Property<int>("DataSheetID")
                        .HasColumnType("int");

                    b.HasIndex("DataSheetID");

                    b.ToTable("SpecialistDoctors");
                });

            modelBuilder.Entity("IngredientMedication", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.Medication", null)
                        .WithMany()
                        .HasForeignKey("UsedInMedicationsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.AppointmentRequest", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Patient", "Patient")
                        .WithMany("Requests")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.SpecialistDoctor", "SpecialistDoctor")
                        .WithMany("Requests")
                        .HasForeignKey("SpecialistDoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("SpecialistDoctor");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Diagnosis", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Patient", "Patient")
                        .WithMany("Dignoses")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Event", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.User", null)
                        .WithMany("Events")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Medication", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Diagnosis", null)
                        .WithMany("PrescribedMedications")
                        .HasForeignKey("DiagnosisId");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Referal", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Diagnosis", "CauseDiagnosis")
                        .WithMany()
                        .HasForeignKey("CauseDiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.Patient", "Patient")
                        .WithMany("Referals")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.Institution", "ReferedInstitition")
                        .WithMany()
                        .HasForeignKey("ReferedInstititionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.SpecialistDoctor", "IssuingDoctor")
                        .WithMany("IssuedReferals")
                        .HasForeignKey("SpecialistDoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CauseDiagnosis");

                    b.Navigation("IssuingDoctor");

                    b.Navigation("Patient");

                    b.Navigation("ReferedInstitition");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Symptom", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Diagnosis", null)
                        .WithMany("Symptoms")
                        .HasForeignKey("DiagnosisId");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.User", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.ContactInfo", "ContactInfo")
                        .WithMany()
                        .HasForeignKey("ContactInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.CustomEvent", null)
                        .WithMany("Attnedees")
                        .HasForeignKey("CustomEventID");

                    b.Navigation("ContactInfo");
                });

            modelBuilder.Entity("MedicalAsisstantSpecialistDoctor", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.SpecialistDoctor", null)
                        .WithMany()
                        .HasForeignKey("AttendingDoctorsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.MedicalAsisstant", null)
                        .WithMany()
                        .HasForeignKey("MedicalAsisstantsID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientSpecialistDoctor", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.SpecialistDoctor", null)
                        .WithMany()
                        .HasForeignKey("SpecialistDoctorsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.MedicalStaffDataSheet", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.DataSheet", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.MedicalStaffDataSheet", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.PatientDataSheet", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.DataSheet", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.PatientDataSheet", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Appointment", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Event", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.Appointment", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.Institution", "PlaceOfVisit")
                        .WithMany()
                        .HasForeignKey("InstitutionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.SpecialistDoctor", "SpecialistDoctor")
                        .WithMany()
                        .HasForeignKey("SpecialistDoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("PlaceOfVisit");

                    b.Navigation("SpecialistDoctor");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.CustomEvent", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.Event", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.CustomEvent", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.MedicationReminder", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.User", "AdministratorOfMedicine")
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.Event", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.MedicationReminder", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministratorOfMedicine");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Administrator", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.MedicalStaffDataSheet", "DataSheet")
                        .WithMany()
                        .HasForeignKey("DataSheetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.User", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.Administrator", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSheet");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.MedicalAsisstant", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.MedicalStaffDataSheet", "DataSheet")
                        .WithMany()
                        .HasForeignKey("DataSheetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.User", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.MedicalAsisstant", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSheet");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Patient", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.PatientDataSheet", "DataSheet")
                        .WithMany()
                        .HasForeignKey("DataSheetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.User", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.Patient", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSheet");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.SpecialistDoctor", b =>
                {
                    b.HasOne("MediLink_BackEnd.Models.MedicalStaffDataSheet", "DataSheet")
                        .WithMany()
                        .HasForeignKey("DataSheetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediLink_BackEnd.Models.User", null)
                        .WithOne()
                        .HasForeignKey("MediLink_BackEnd.Models.SpecialistDoctor", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSheet");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Diagnosis", b =>
                {
                    b.Navigation("PrescribedMedications");

                    b.Navigation("Symptoms");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.User", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.CustomEvent", b =>
                {
                    b.Navigation("Attnedees");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.Patient", b =>
                {
                    b.Navigation("Dignoses");

                    b.Navigation("Referals");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("MediLink_BackEnd.Models.SpecialistDoctor", b =>
                {
                    b.Navigation("IssuedReferals");

                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
